[workspace]
members = [
    "graphyte_engine",
    "graphyte_game",
    "graphyte_math",
    "graphyte_utils",
    "graphyte_graphics_stage",
    "graphyte_winit_platform",
    "graphyte_asset_library",
    "graphyte_scripting_stage",
    "mesh",
    "tools/gltf_extract_meshes",
]
