application_name: magnetar
engine_name: Magnetar Engine

application_major_version: 0
application_minor_version: 1
application_patch_version: 0

engine_major_version: 0
engine_minor_version: 1
engine_patch_version: 0

startup_scene: basic scene