[package]
name = "shader_compiler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gyt_shaderc"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1", features = ["derive"] }
shaderc = "0.8"
spirv-reflect = "0.2"
shader = { path = "../../shader" }
mesh = { path = "../../mesh" }
