[package]
name = "egui_base"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
winit_platform = { path = "../../winit_platform" }
graphics = { path = "../../graphics" }
egui = { version = "0.18" }
winit = "0.26"
egui-winit = "0.18"
egui-winit-ash-integration = "0.2"
