[package]
name = "spacebar_utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12"
termcolor = "1.1"
num-traits = "0.2"
rayon = "1.5"
num_cpus = "1.13"
smol = "1.2.5"