[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
engine = { path = "../engine" }
graphics = { path = "../graphics" }
winit_platform = { path = "../winit_platform" }

ash = "0.37"
egui = "0.18"
winit = "0.26"
gpu-allocator = "0.18"
egui-winit = "0.18"
