---
buffers:
  - descripor:
      stride: 12
      elements:
        - offset: 0
          format: F32x3
    buffer_purpose: InterleavedVertexBuffer
    buffer:
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 63
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 0
      - 191
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 191
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 128
      - 63
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 2
      - 0
      - 1
      - 0
      - 2
      - 0
      - 3
      - 0
      - 1
      - 0
      - 4
      - 0
      - 6
      - 0
      - 5
      - 0
      - 6
      - 0
      - 7
      - 0
      - 5
      - 0
      - 8
      - 0
      - 10
      - 0
      - 9
      - 0
      - 10
      - 0
      - 11
      - 0
      - 9
      - 0
      - 12
      - 0
      - 14
      - 0
      - 13
      - 0
      - 14
      - 0
      - 15
      - 0
      - 13
      - 0
      - 16
      - 0
      - 18
      - 0
      - 17
      - 0
      - 18
      - 0
      - 19
      - 0
      - 17
      - 0
      - 20
      - 0
      - 22
      - 0
      - 21
      - 0
      - 22
      - 0
      - 23
      - 0
      - 21
      - 0