prefer_integrated_gpu: true
prevent_tearing: false
limit_frame_rate: false
preferred_frames_in_flight: 2

use_transfer_queues: true
#preferred_gpu: "Intel(R) UHD Graphics 630"

instance_extension_names: []
instance_extension_names_debug: []

instance_validation_layer_names: []
instance_validation_layer_names_debug: [
  "VK_LAYER_KHRONOS_validation"
]

default_window_title: "Graphyte - Vulkan Renderer"
default_window_width: 800
default_window_height: 600